version: '3.8'

services:
  # Development overrides for the app service
  app:
    build:
      target: builder
    environment:
      NODE_ENV: development
      # Authentication Configuration (can be toggled for development)
      AUTH_ENABLED: true
      JWT_SECRET: dev-jwt-secret-key-not-for-production
      JWT_EXPIRES_IN: 24h
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "start:dev"]
    ports:
      - "3000:3000"
      - "9229:9229"  # Debug port
